baseURL = "https://jailingineni.github.io/CharitableInvestmentsClub/"
languageCode = "en-us"
title = "Charitable People"
theme = "timer-hugo"
publishDir = ".."


# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Service"
url     = "service"
weight  = 3
[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "HI, WE ARE THE CHARITABLE INVESTMENTS CLUB"
description = "Our club was made to help teach students about investment and better the community at the same time."
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "CHARITABLE"
[[params.banner.flipText]]
title   = "INVOLVED"
[[params.banner.flipText]]
title   = "EDUCATIONAL"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT THE CLUB"
content = "6 teenagers started this club with an interest in both investing, education, and charity. Together, they learned about the stock market and investments, and finally decided to put together everything they knew to help the community. <br> <br> Together, we created an account worth $2,100. Our goal is to use what we’ve learned to grow that number through investing, and donate any and all of the profits we make to a good cause in the local area. Along the way, we will also conduct activities related to volunteering and giving back, which might entail some fundraising as well. COVID-19 brought unprecedented times, and we want to do our part in helping our community in anyway we can. It’ll be a great learning experience for us, in both investing and altruism. We are ready to everything we can… Are you ready to help us?"
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
